import introText from "./../prompts/introText.md";
import frontMatterText from "./../prompts/frontmatterText.md";
import contentText from "./../prompts/contentText.md";
import dataViewsText from "./../prompts/dataviewsText.md";
/**
 * Settings for the GPT Helper plugin
 */
export interface DigitalGardenerSettings {
	/**
	 * Root Application Folder
	 */
	rootFolder: string;
	/**
	 * The users OpenAI API Key
	 */
	openAIAPIKey: string;
	/**fv
	 * The OpenAI Model to use
	 */
	openAIModel: string;
	/**
	 * The path to save new files generated by GPT
	 */
	outputPath: string;

	/**
	 * The temperature to use when generating text
	 */
	oaiTemperature: number;

	/**
	 * The maximum number of tokens to use when generating text
	 */
	oaiMaxTokens: number;

	/**
	 * The intro text to use when generating new files
	 */
	introText: string;
	/**
	 * The content text to use when generating new files
	 */
	contentText: string;
	/**
	 * The frontmatter text to use when generating new files
	 */
	frontmatterText: string;
	/**
	 * The data view text to use when generating new files
	 */
	dataViewText: string;

	/**
	 * The agent user name
	 */
	userName: string;
	/**
	 * The agent user pronouns
	 */
	userPronouns: string;
	/**
	 * The agent user bio
	 */
	userBio: string;
	/**
	 * The agent user languages
	 */
	userLanguages: string;

	/**
	 * The level of emoji usage
	 */
	emojiLevel: EmojiLevel;
}

export type EmojiLevel = "none" | "low" | "medium" | "high";

export const DEFAULT_SETTINGS: DigitalGardenerSettings = {
	rootFolder: "",
	userName: "",
	userPronouns: "",
	userBio: "",
	userLanguages: "English (en-gb)",
	openAIAPIKey: "",
	openAIModel: "gpt-35-turbo",
	outputPath: "gpt-garden",
	oaiTemperature: 0.7,
	oaiMaxTokens: 10000,
	introText: introText.raw,
	contentText: contentText.raw,
	frontmatterText: frontMatterText.raw,
	dataViewText: dataViewsText.raw,
	emojiLevel: "none",
};

export const AVAILABLE_MODELS = {
	"gpt-4-vision-preview": "GPT4 Turbo + Vision",
	"gpt-4-1106-preview": "GPT4 Turbo",
	"gpt-4": "GPT-4",
	"gpt-35-turbo": "GPT3.5 Turbo",
};
